# Reviewer
- id: iclr-2025
  role: reviewer
  venue: ICLR, 2025
- id: aaai-2025
  role: reviewer
  venue: AAAI, 2025
- id: siggraph-sia-2024
  role: reviewer
  venue: SIGGRAPH Asia, 2024
- id: eccv-2024
  role: reviewer
  venue: ECCV, 2024
- id: siggraph-2024
  role: reviewer
  venue: SIGGRAPH, 2024
- id: cvpr-2024
  role: reviewer
  venue: CVPR, 2024
- id: iclr-2024
  role: reviewer
  venue: ICLR, 2024
- id: neurips-2023
  role: reviewer
  venue: NeurIPS, 2023
- id: siggraph-asia-2023
  role: reviewer
  venue: SIGGRAPH Asia, 2023
- id: cad-2023
  role: reviewer
  venue: Computer Aided Design, 2023
- id: graphical-models-2023
  role: reviewer
  venue: Graphical Models, 2023
- id: graphics-replicability-stamp-2023
  role: reviewer
  venue: Graphics Replicability Stamp Initiative, 2023
